AutodijeloviAsp/AutodijeloviAsp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutodijeloviAsp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AutodijeloviAsp/AutodijeloviAsp/Controllers/KorisniksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutodijeloviAsp.Models;

namespace AutodijeloviAsp.Controllers
{
    public class KorisniksController : Controller
    {
        private AutodijeloviContext db = new AutodijeloviContext();

        // GET: Korisniks
        public ActionResult Index()
        {
            return View(db.Korisnik.ToList());
        }

        // GET: Korisniks/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Korisnik korisnik = db.Korisnik.Find(id);
            if (korisnik == null)
            {
                return HttpNotFound();
            }
            return View(korisnik);
        }

        // GET: Korisniks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Korisniks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KorisnikID,userName,password,email,datumRegistrovanja,popust,brojNarudzbi")] Korisnik korisnik)
        {
            if (ModelState.IsValid)
            {
                db.Korisnik.Add(korisnik);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(korisnik);
        }

        // GET: Korisniks/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Korisnik korisnik = db.Korisnik.Find(id);
            if (korisnik == null)
            {
                return HttpNotFound();
            }
            return View(korisnik);
        }

        // POST: Korisniks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KorisnikID,userName,password,email,datumRegistrovanja,popust,brojNarudzbi")] Korisnik korisnik)
        {
            if (ModelState.IsValid)
            {
                db.Entry(korisnik).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(korisnik);
        }

        // GET: Korisniks/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Korisnik korisnik = db.Korisnik.Find(id);
            if (korisnik == null)
            {
                return HttpNotFound();
            }
            return View(korisnik);
        }

        // POST: Korisniks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Korisnik korisnik = db.Korisnik.Find(id);
            db.Korisnik.Remove(korisnik);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutodijeloviAsp/AutodijeloviAsp/Views/Home/About.cshtml
@{
    ViewBag.Title = "";
}
<h2>@ViewBag.Title.</h2>


<script>
    filterSelection("all")
    function filterSelection(c) {
        var x, i;
        x = document.getElementsByClassName("filterDiv");
        if (c == "all") c = "";
        // Add the "show" class (display:block) to the filtered elements, and remove the "show" class from the elements that are not selected
        for (i = 0; i < x.length; i++) {
            w3RemoveClass(x[i], "show");
            if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
        }
    }

    // Show filtered elements
    function w3AddClass(element, name) {
        var i, arr1, arr2;
        arr1 = element.className.split(" ");
        arr2 = name.split(" ");
        for (i = 0; i < arr2.length; i++) {
            if (arr1.indexOf(arr2[i]) == -1) {
                element.className += " " + arr2[i];
            }
        }
    }

    // Hide elements that are not selected
    function w3RemoveClass(element, name) {
        var i, arr1, arr2;
        arr1 = element.className.split(" ");
        arr2 = name.split(" ");
        for (i = 0; i < arr2.length; i++) {
            while (arr1.indexOf(arr2[i]) > -1) {
                arr1.splice(arr1.indexOf(arr2[i]), 1);
            }
        }
        element.className = arr1.join(" ");
    }

    // Add active class to the current control button (highlight it)
    var btnContainer = document.getElementById("myBtnContainer");
    var btns = btnContainer.getElementsByClassName("btn");
    for (var i = 0; i < btns.length; i++) {
        btns[i].addEventListener("click", function () {
            var current = document.getElementsByClassName("active");
            current[0].className = current[0].className.replace(" active", "");
            this.className += " active";
        });
    }
</script>
<style>
    body {
        background-color: black;
        background-image: url(http://sf.co.ua/14/06/wallpaper-1130835.jpg);
        background-size: 1400px 1300px;
        background-repeat: no-repeat;
        background-position: center;
    }

    .slika {
        margin-left:15%;
        opacity: 0.4;
    }

        .dg{
            margin-left:10%;
            margin-top:2%;
        }

    .bmw {
        background-image: url(http://galleryautomo.com/wp-content/uploads/2016/03/bmw_logo_black_background_cool_car_wallpapers_.jpg);
        background-size: cover;
        background-position:center;
        border-radius:50%;
        padding: 40px 70px;
    }
    .audi {
        background-image: url(http://www.hdwallpaperspulse.com/wp-content/uploads/2014/03/25/r5.jpeg);
        background-size: cover;
        background-position: center;
        border-radius: 50%;
        padding: 40px 70px;
    }

    .mercedes {
        background-image: url(http://mbworld.org/forums/attachments/off-topic/174330d1263691675-mercedes-amg-backgrounds-iphone-mb_logo_white.jpg);
        background-size: cover;
        background-position: center;
        border-radius: 50%;
       
        padding: 40px 70px;
    }


    .porsche {
        background-image: url(https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/4-porsche-logo-porsche-logo.jpg);
        background-size: cover;
        background-position: center;
        border-radius: 50%;
        padding: 40px 70px;
    }

    .w {
        background-image: url(https://i.ytimg.com/vi/TXDh7XG0GZY/maxresdefault.jpg);
        background-size: cover;
        background-position: center;
        border-radius: 50%;
        padding: 40px 70px;
    }

    .skoda {
        background-image: url(http://logodatabases.com/wp-content/uploads/2012/03/skoda-logo-black.jpg);
        background-size: cover;
        background-position: center;
        border-radius: 50%;
        padding: 40px 70px;
    }

    .s{
        margin-top:5%;
    }

    .m {
        margin-top: 5%;
    }

    .v {
        margin-top: 5%;
    }
</style>

<img class="slika" src="~/Slike/KATALOG.jpg" height="200" />
<header>

    <hr />
</header>


<!-- The filterable elements. Note that some have multiple class names (this can be used if they belong to multiple categories) -->
<div class="container dg">
    <div class="row">

        <div class="col-sm-4">
            <div class="container">
                <form action="https://www.bmw.com/en/bmw-models.html">
                    <button class="bmw"></button>
                </form>
            </div>
            <div class="container v">
                <form action="http://www.vw.com">
                    <button class="w"></button>
                </form>

            </div>

        </div>

        <div class="col-sm-4">
            <div class="container">
                <form action="https://www.porsche.com/?gclid=Cj0KCQjwgMnYBRDRARIsANC2dflToPcZ_mO7KJlVZOtL0_i78pUGXVGM-rGxHQIDKu68ZEN3sseChV4aApfLEALw_wcB">
                    <button class="porsche"></button>
                </form>
            </div>
            <div class="container m">
                <form action="https://www.mercedes-amg.com/en/vehicles.html">
                    <button class="mercedes"></button>
                </form>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="container">
                <form action="https://www.audi.com/en/models.html">
                    <button class="audi"></button>
                </form>
            </div>

            <div  class="container s">
                <form action="http://www.skoda-auto.com/">
                    <button class="skoda"></button>
                </form>
            </div>
        </div>
    </div>

 
</div>

        

AutodijeloviAsp/AutodijeloviAsp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "";
}
<h2></h2>
<h3></h3>

<style>

    body {
        background-color: black;
        background-image: url(http://sf.co.ua/14/06/wallpaper-1130835.jpg);
        background-size: 1400px 1300px;
        background-repeat: no-repeat;
        background-position: center;
        color: white;
    }
</style>

<h1>Kontakt informacije: </h1>
<hr />
<address>
    <br />
    Sarajevo, Kamena ulica br.10<br />
    <abbr title="Phone">Broj telefona:033/123-456</abbr>

</address>

<address>
    <strong>Email:</strong>   <a href="mailto:Support@example.com">PosaljiMail@gmail.com</a><br />

</address>

AutodijeloviAsp/AutodijeloviAsp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}



<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
        var slideIndex = 1;
        showSlides(slideIndex);

        function plusSlides(n) {
            showSlides(slideIndex += n);
        }

        function currentSlide(n) {
            showSlides(slideIndex = n);
        }

        function showSlides(n) {
            var i;
            var slides = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("dot");
            if (n > slides.length) { slideIndex = 1 }
            if (n < 1) { slideIndex = slides.length }
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
            }
            slides[slideIndex - 1].style.display = "block";
            dots[slideIndex - 1].className += " active";
        }
    </script>
    <link rel="stylesheet" type="text/css" href="styles.css" />
    <style>
        /* Remove the navbar's default rounded borders and increase the bottom margin */
        .navbar {
            margin-bottom: 50px;
            border-radius: 0;
            color: Black;
        }

        li {
            border-right: 1px solid #bbb;
            border-left: 1px solid #bbb;
        }

            li:last-child {
                border-right: none;
            }

        /* Remove the jumbotron's default bottom margin */
        .jumbotron {
            padding-top: 240px;
            background-image: url(https://wallup.net/wp-content/uploads/2016/01/278423-zenvo-car-blue_cars-orange-luxury_cars-zenvo_st1.jpg);
            background-size: 100% 100%;

        }

            .jumbotron .h1, .jumbotron h1 {
                color: LightBlue;
                font-size: 80px;
                font-weight: bold;
                font-family: 'Shift', sans-serif;
                position: absolute;
                left: 220px;
               bottom: 250px;
            }

        .panel-body img {
            height: 250px;
            width: 100%;
        }
        /* Add a gray background color and some padding to the footer */
        footer {
            padding: 25px;
        }

        body {
            background-color: Black;
        }
        h3{
        color: LightBlue;
        font-size: 40px;
        font-weight: bold;
        }
        h4{
        color:LightBlue;
        font-size: 20px;
        }
        h5{
        color:LightBlue;
        font-size: 20px;
        }
        h6{
        color: LightBlue;
        font-size: 20px;
        
        }
        h7{
            color:lightblue;
            font-size:25px;
        }
        h8 {
            color: lightblue;
            font-size: 30px;
            text-align:center;
            margin-left:15%;
            
        }
        .sign {
            background-color: lightblue;
            color: black;
            font-weight: bold;
            margin-left: 22%;
            padding: 4px 60px;
        }
        .imgcontainer {
            text-align: center;
            position: relative;
           
        }

        img.avatar {
            border-radius: 50%;
        }
        .sifra{
            color:lightblue;
            font-size:15px;
        }
        .email{
            color:lightblue;
            font-size:15px;
        }
        .zapamti{
            color:lightblue;
            font-size:15px;
        }
        .login{
            background-color:lightblue;
            color:black;
            font-weight:bold;
            margin-left: 10%;
            padding: 4px 40px;
        }
        .ime{
            color:lightblue;
            font-size: 15px;
        }
        .zab{
            color:lightblue;
            font-size: 15px;
        }
        .log{
            position:relative;
            left:150px;
        }
        
        .racun{
            position:relative;
            left:200px;
        }
        
        * {box-sizing: border-box}

.mySlides {display: none}
.mySlides .img, .mySlides img {vertical-align: middle; height:400px; width:400px; }

/* Slideshow container */
.slideshow-container {
  max-width: 800px;
  position: relative;
  margin: auto;
}

/* Next & previous buttons */
.prev, .next {
  cursor: pointer;
  position: absolute;
  top: 50%;
  width: auto;
  padding: 16px;
  margin-top: -22px;
  color: white;
  font-weight: bold;
  font-size: 18px;
  transition: 0.6s ease;
  border-radius: 0 3px 3px 0;
}

/* Position the "next button" to the right */
.next {
  right: 0;
  border-radius: 3px 0 0 3px;
}

/* On hover, add a black background color with a little bit see-through */
.prev:hover, .next:hover {
  background-color: rgba(0,0,0,0.8);
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 20px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  cursor: pointer;
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}



/* Fading animation */




/* On smaller screens, decrease text size */
@@media only screen and (max-width: 300px) {
  .prev, .next,.text {font-size: 11px}
}
    </style>
</head>
<body>

    <div class="jumbotron" style="">
        <div class="container text-center">
            <h1>AUTODIJELOVI KAMENI</h1>
            <p></p>
        </div>
    </div>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
            </div>
            
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#pocetna">Pocetna</a></li>
                <li>@Html.ActionLink("Katalog", "About", "Home")</li>
                
                <!--<li><a data-toggle="tab" href="#kontakt">Kontakt</a></li> -->
                <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                <li>@Html.ActionLink("Log In", "Login", "Account")</li>
                <li>@Html.ActionLink("Sign Up", "Create", "Korisniks")</li>




            </ul>
            
        </div>
    </nav>

    

        <div class="tab-content">
            
            
            <div id="pocetna" class="tab-pane fade in active">
                <div class="row">
                    <div class="col-sm-4">
                        <img src="~/Slike/kamenii.jpg" class="img-responsive" alt="Cinque Terre" height="400" width="400">
                    </div>
                    <div class="col-sm-8">
                        <h3>Dobrodošli ! </h3>
                        <h4>Uživajte u mnogobrojnim pogodnostima naše veleposlovnice.</h4>
                        <h5>Online naručivanje i kupovina autodijelova uvodi revoluciju u poslovanju.</h5>
                        <h6>Brze i efikasne usluge su napokon svima na raspolaganju.</h6>
                    </div>
                </div>
            </div>

            <div id="login" class="tab-pane fade">
                <div class="container log">
                    <form>
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="imgcontainer">
                                    <img src="~/Slike/cvikeraš.png" alt="Avatar" class="avatar" height="200" width="200">
                                </div>
                            </div>

                            <div class="col-sm-8">
                                <h7>Unesite tražene podatke: </h7>
                                <div class="form-group">
                                    <label class="label email" emailfor="email">Email:</label>
                                    <input type="email" class="form-control" id="email" placeholder="Unesite email">
                                </div>
                                <div class="form-group">
                                    <label class="label sifra" for="pwd">Šifra:</label>
                                    <input type="password" class="form-control" id="pwd" placeholder="Unesite šifru">
                                </div>
                                <div class="checkbox">
                                    <label class="label zapamti"><input type="checkbox"> Zapamti podatke</label>
                                    <span class="psw zab">Zaboravili ste <a href="#">šifru?</a></span>
                                </div>
                                <button type="submit" class="button login" >Log In</button>
                               
                            </div>
                        </div>
                    </form>
                </div>

            </div>

            <div id="korisnickiracun" class="tab-pane fade">
                <div class="container racun">
                    <h8>Unesite tražene podatke:</h8>
                    <form action="action_page.php">

                        <div class="row">
                            <div class="col-sm-4">

                                <div class="form-group">
                                    <label class="label email" emailfor="email">Email:</label>
                                    <input type="email" class="form-control" id="email" placeholder="Unesite email">
                                </div>
                                <div class="form-group">
                                    <label class="label ime" for="pwd">Odaberite korisničko ime:</label>
                                    <input type="password" class="form-control" id="pwd" placeholder="Unesite korisičko ime">
                                   
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label class="label sifra" for="pwd">Šifra:</label>
                                    <input type="password" class="form-control" id="pwd"  placeholder="Unesite šifru" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" required>
                                </div>

                                <div class="form-group">
                                    <label class="label sifra" for="pwd">Ponovo unesite šifru:</label>
                                    <input type="password" class="form-control" id="pwd" placeholder="Unesite šifru">
                                </div>

                                <p>Kreirajući račun pristajete na naše<a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>
                                

                            </div>
                        </div>
                        <button type="submit" class="button sign">Sign Up</button>
                    </form action="action_page.php">
                </div>
            </div>

            

           <div id="kontakt" class="tab-pane fade">

           </div>

                    
                </div>

            




</body>
</html>